all: sum calc calc2 calc3

sum: sum.cpp
	g++ -std=c++11 -o sum sum.cpp
	./sum < sum.txt

calc: calc.cpp
	g++ -std=c++11 -o calc calc.cpp
	./calc < calc.txt

calc2: calc2.cpp
	g++ -std=c++11 -o calc2 calc2.cpp
	./calc2 < calc2.txt

calc3: calc3.cpp
	g++ -std=c++11 -o calc3 calc3.cpp
	./calc3 < calc3.txt

clean:
	rm sum calc calc2 calc3


